spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springbootbase??useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: root
      password: 1234

##########################日志
logging:
    level:
        org:
            springframework:
                web: DEBUG
##########################日志




#environments :
#  dev:
#
#spring:
#
#  banner:
#    location: aa.txt  #横幅加载
#    charset: UTF-8     #横幅编码
#    image:
#      location: aa.jpg   #横幅图片路径


#logging:
#  level:
#    root: WARN
#    org:
#      springframework:
#        web: DEBUG
#      hibernate: ERROR

