
##########################日志
logging:
    level:
        org:
            springframework:
                web: DEBUG
##########################日志

#############################beetl
beetl:
    templatesPath: /templates         #单独配置的
    delimiter-statement-start: ==>   #开始结束标签(yaml不允许@开头)
    delimiter-statement-end: null
    resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
    resource-tagsuffix: tag
    resource-auto-check: true       #是否检测文件变化,开发用true合适，但线上要改为false
    resource-function-suffix: html
#############################beetl

#############################actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 10111
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always
#############################actuator
#############################mybatis-plus

mybatis-plus: 
    mapper-locations: classpath:com/**/mapper/*Mapper.xml

    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.myyd.entity

    #枚举扫描，多个package用逗号或者分号分隔
    #typeEnumsPackage: com.burt.*.entity.enums

    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    global-config.id-type: 2

    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    global-config.field-strategy: 2

    #驼峰下划线转换
    global-config.db-column-underline: true

    #mp2.3+ 全局表前缀 mp_
    #global-config.table-prefix: mp_

    #刷新mapper 调试神器
    global-config.refresh-mapper: true

    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    configuration.map-underscore-to-camel-case: true

    configuration.cache-enabled: false

##mybatis-plus end

########################### server
########################### server
########################### jpa
#jpa:
#    # 配置 DBMS 类型
#    database: MYSQL
#    # 配置是否将执行的 SQL 输出到日志
#    show-sql: true
#    properties:
#        hibernate:
#            hbm2ddl:
#          # 配置开启自动更新表结构
#                auto: update
########################### jpa

#############################spring
spring:
    activemq:    #############################ActiveMq
        in-memory: true
        pool:
            enabled: false
    banner:
        location: aa.txt  #横幅加载
        charset: UTF-8     #横幅编码
        image:
          location: aa.jpg   #横幅图片路径
    profiles:
        active: dev

#############################一些自定义配置


---
spring:
  profiles: dev
#DATABASE CONFIG 注意这里连得是sql server



# 下面为连接池的补充设置，应用到上面所有数据源中
datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootbase??useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 1234
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
    useGlobalDataSourceStat: true


yd:
    name: 喻冬
    sex: 男
    age: 25

---
spring:
  profiles: test

yd:
    name: 喻冬1
    sex: 男1
    age: 251