
server:
    port: 8081
#    datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/springbootbase??useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
#      username: root
#      password: 1234
#

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/testspringproject?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 20
        test-while-idle: true
        validation-query: select 1
        default-auto-commit: false
        min-idle: 15
        initial-size: 15

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    jackson:
        serialization:
            indent-output: true

mysecurity:
    socialProperties:
        qqProperties:
            provider-id: qq
            app-id: 1107982260
            app-secret: Be0YqRSz2WhGPxgw
    browser:
#        loginPage: /demo-signLogin.html
        loginType: JSON
    validate:
        image:
            width: 100
            height: 32
            length: 6
            expireIn: 60
        smsCode:
            length: 6
            expireIn: 60
#            url;
#            url:

###########################日志
#logging:
#    level:
#        org:
#            springframework:
#                web: DEBUG
###########################日志




#environments :
#  dev:
#
#spring:
#
#  banner:
#    location: aa.txt  #横幅加载
#    charset: UTF-8     #横幅编码
#    image:
#      location: aa.jpg   #横幅图片路径


#logging:
#  level:
#    root: WARN
#    org:
#      springframework:
#        web: DEBUG
#      hibernate: ERROR

