
server:
    port: 80
#    datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/springbootbase??useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
#      username: root
#      password: 1234
#
    session: 60
spring:
    datasource:
        url: jdbc:mysql://120.78.80.130:3306/testspringproject?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 20
        test-while-idle: true
        validation-query: select 1
        default-auto-commit: false
        min-idle: 15
        initial-size: 15

  # redis配置，默认没有密码
#    redis:
#        host: 47.92.1.158
#        port: 6379
#        password: ladlee123
#        jedis:
#            pool:
#                min-idle: 8
#                max-idle: 500
#                max-active: 2000
#                max-wait: 10000
#        timeout: 0

  # session 存储到 redis，实现分布式 session
#    session:
#        store-type: redis
#        redis:
#            namespace: febs:spring:session

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    jackson:
        serialization:
            indent-output: true

mysecurity:
    socialProperties:
        qqProperties:
            provider-id: qq
            app-id: 101521863
            app-secret: a4098bc6065314509978c77952d5a15e
    browser:
#        loginPage: /demo-signLogin.html
        loginType: JSON
    validate:
        image:
            width: 100
            height: 32
            length: 6
            expireIn: 60
        smsCode:
            length: 6
            expireIn: 60
#            url;
#            url:

###########################日志
#logging:
#    level:
#        org:
#            springframework:
#                web: DEBUG
###########################日志




#environments :
#  dev:
#
#spring:
#
#  banner:
#    location: aa.txt  #横幅加载
#    charset: UTF-8     #横幅编码
#    image:
#      location: aa.jpg   #横幅图片路径


#logging:
#  level:
#    root: WARN
#    org:
#      springframework:
#        web: DEBUG
#      hibernate: ERROR

