server:
    port: 80

    session: 60
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/manage-admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 20
        test-while-idle: true
        validation-query: select 1
        default-auto-commit: false
        min-idle: 15
        initial-size: 15
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    jackson:
        serialization:
            indent-output: true
