server:
    port: 80   # 端口号
    session: 60   # session的过期时间
spring:
    datasource:
        url: jdbc:mysql://120.78.80.130:3306/manage-admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 20
        test-while-idle: true
        validation-query: select 1
        default-auto-commit: false
        min-idle: 15
        initial-size: 15
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    jackson:
        serialization:
            indent-output: true


logging:
    level:
        root: INFO






mysecurity:
    socialProperties:
        qqProperties:
            provider-id: qq
            app-id: 101521863
            app-secret: a4098bc6065314509978c77952d5a15e
    browser:
#        loginPage: /demo-signLogin.html
        loginType: JSON
    validate:
        image:
            width: 100
            height: 32
            length: 6
            expireIn: 60
        smsCode:
            length: 6
            expireIn: 60