mysecurity:
    socialProperties:
        qqProperties:
            provider-id: qq
            app-id: 101521863
            app-secret: a4098bc6065314509978c77952d5a15e
    browser:
#        loginPage: /demo-signLogin.html
        loginType: JSON
    validate:
        image:
            width: 100
            height: 32
            length: 6
            expireIn: 60
        smsCode:
            length: 6
            expireIn: 60

ydsecurity:
    validate_code:
        image_code:
            width: 100
            height: 32
            length: 6
            expireIn: 180
            url:
        sms_code:
            length: 6
            expireIn: 180
            url:



server:
    port: 80  # 端口号
    tomcat:
        max-threads: 100
        min-spare-threads: 20
        connection-timeout: 6000
#    servlet:
#      session:
#        timeout: 60
          # 默认为30分钟，这里的单位是秒
#          server.session.timeout = 10 * 60

spring:
    redis:   #redis内存数据库地址配置
        database: 0
        timeout: 5000
        host: 47.92.1.158
        password: ladlee123
        port: 6379
        lettuce:
          pool:
            max-active: 500
            max-idle: 100
            min-idle: 20
            max-wait: -1ms
            shutdown-timeout: 100


    session:            #session使用redis进行储存
        store-type: redis
        redis:
            namespace: authSession
            flush-mode: immediate
#    cache:    #cache使用redis储存
#        type: redis


    datasource:
        url: jdbc:mysql://120.78.80.130:3306/manage-admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 20
        test-while-idle: true
        validation-query: select 1
        default-auto-commit: false
        min-idle: 15
        initial-size: 15
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
    jackson:
        serialization:
            indent-output: true
    thymeleaf:
        encoding: UTF-8
        mode: HTML
        enabled: true
        check-template: true
        cache: false


