environments :
  dev:

spring:

  banner:
    location: aa.txt  #横幅加载
    charset: UTF-8     #横幅编码
    image:
      location: aa.jpg   #横幅图片路径



logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

