
spring:
    application:
        name: eureka-server
    profiles:
        active: server3
    cloud:
        config:
            enabled: false
---
spring:
    profiles: server3
server:
    port: 9093
eureka:
    instance:
        instance-id: eureka-server-9093
        prefer-ip-address: true
        hostname: eureka-server-hostname3
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://server1:9091/eureka/,http://server2:9092/eureka/
